version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: "car-ui-app-dev"
    volumes:
      - ./src:/app/src
    ports:
      - "4200:4200"
