version: "3"
services:
  nginx:
    image: nginx
    container_name: 'nginx'
    depends_on:
      - frontend
    volumes:
      - shared:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9090:80"
  frontend:
    build:
      context: .
    container_name: "car-ui-app"
    volumes:
      - shared:/app/dist
volumes:
  shared: {}
